# remote_theme: pages-themes/merlot@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
theme: minimal
title: Exploring Generating Functions
author: Jeffrey S. Haemer
description: I learn how to think about and work with generating functions.
markdown: GFM
