# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# remote_theme: jekyll/minima
remote_theme: ryanmcdermott/jekyll-latex
title: Exploring Generating Functions
author: Jeffrey S. Haemer
description: I learn how to think about and work with generating functions.
markdown: GFM
