remote_theme: jsh/minima
title: Exploring Generating Functions
author:
  name: Jeffrey S. Haemer
  email: jeffrey.haemer@gmail.com
description: I learn how to think about and work with generating functions.
show_excerpts: true
