# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: jsh/minima
# remote_theme: LeNPaul/Lagrange
title: Exploring Generating Functions
author: Jeffrey S. Haemer
description: I learn how to think about and work with generating functions.
show_excerpts: true
